name: Build and deploy Python app to Azure Web App - prueba-tecnica-api-rd

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment and install dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r backend/requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            backend/
            !antenv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EECA4BB9C5204007B66C3C2B0C008AC9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_26AE22CCAAB24D70946C4500EC13B0A5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_030726292549452587F5A123DDC66766 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'prueba-tecnica-api-rd'
          slot-name: 'Production'
          startup-command: 'cd /home/site/wwwroot && pip install -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000'
